### ISSUE TITLE
make podman/docker-build failed

### ISSUE THREAD

**Issue by Koncpa** [latchset/tang-operator#248]
# Environment
 * OS / version: Fedora-rawhide
 * Processor architecture:  x86_64
 * Tang-operator version: Compiling latest upstream code 

# Description 

`make podman/docker-build` fail with error, but image is built and prepared for deployment. Same scenario appeared for `make bundle `. It was tested for other versions of OS, but just for Fedora-rawhide end up with errors.

## Expected behavior vs. actual behavior 

Build of image and bundle will be success without errors vs. Even though the image is eventually built, errors appeared during the build.

## Steps to reproduce problem
1. Have prepared Fedora-Rawhide host
2. Clone tang-operator repository
3. build image make podman-build

# Relevant logs

```
rpm -qa | grep go
google-noto-fonts-common-20230801-6.fc40.noarch
google-noto-sans-mono-vf-fonts-20230801-6.fc40.noarch
google-noto-sans-vf-fonts-20230801-6.fc40.noarch
google-noto-serif-vf-fonts-20230801-6.fc40.noarch
libgomp-14.0.1-0.4.fc40.x86_64
libargon2-20190702-5.fc40.x86_64
gobject-introspection-1.79.1-4.fc40.x86_64
python3-gobject-base-3.46.0-3.fc40.x86_64
python3-gobject-base-noarch-3.46.0-3.fc40.noarch
python3-configobj-5.0.8-6.fc40.noarch
binutils-gold-2.41-32.fc40.x86_64
qemu-user-static-hexagon-8.2.0-7.fc40.x86_64
golang-src-1.22~rc2-1.fc40.noarch
go-filesystem-3.3.1-3.fc40.x86_64
golang-1.22~rc2-1.fc40.x86_64
golang-bin-1.22~rc2-1.fc40.x86_64
```

```
[tang-operator]# make podman-build
/root/tang-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa094fe]

goroutine 65 [running]:
go/types.(*Checker).handleBailout(0xc0002fee00, 0xc0011f7d40)
	/usr/lib/golang/src/go/types/check.go:367 +0x88
panic({0xbc4180?, 0x12acc40?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdbcb78, 0x12b53a0})
	/usr/lib/golang/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/lib/golang/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdbcb78?, 0x12b53a0?})
	/usr/lib/golang/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdc2ef0, 0x1281500}, 0xc0002fee00, 0x12b53a0, 0xc0011f74b0)
	/usr/lib/golang/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0002fee00, 0xc0012026c0, 0x12b53a0)
	/usr/lib/golang/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0002fee00, 0xc0012026c0, {0xdbcba0, 0xc00027ab60})
	/usr/lib/golang/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc0002fee00, 0xc0012026c0, {0xdbcba0, 0xc00027ab60}, {0xc912e4, 0x14})
	/usr/lib/golang/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc0002fee00, 0xc0011f8240, 0xc0012026c0)
	/usr/lib/golang/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc0002fee00, 0xc0011f8240, {0xdbf7e8, 0xc000fd4540}, {0xdbf7e8, 0xc000fd4560}, 0x0)
	/usr/lib/golang/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc0002fee00, {0xdc85d8, 0xc0011f8240}, 0x0)
	/usr/lib/golang/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc0002fee00)
	/usr/lib/golang/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0002fee00, {0xc00020a780, 0x5, 0x5})
	/usr/lib/golang/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/lib/golang/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002b7020, 0xc00087f820)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc00087f820)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc0007e8cc0, 0xc00087f820)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x4e?)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 43
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:260 +0x1c5
make: *** [Makefile:91: manifests] Error 2
```

```
[tang-operator]# make bundle
/root/tang-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa094fe]

goroutine 65 [running]:
go/types.(*Checker).handleBailout(0xc00030ee00, 0xc000fd3d40)
	/usr/lib/golang/src/go/types/check.go:367 +0x88
panic({0xbc4180?, 0x12acc40?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdbcb78, 0x12b53a0})
	/usr/lib/golang/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/lib/golang/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdbcb78?, 0x12b53a0?})
	/usr/lib/golang/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdc2ef0, 0x1281500}, 0xc00030ee00, 0x12b53a0, 0xc000fd34b0)
	/usr/lib/golang/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc00030ee00, 0xc001221c80, 0x12b53a0)
	/usr/lib/golang/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc00030ee00, 0xc001221c80, {0xdbcba0, 0xc000274e00})
	/usr/lib/golang/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc00030ee00, 0xc001221c80, {0xdbcba0, 0xc000274e00}, {0xc912e4, 0x14})
	/usr/lib/golang/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc00030ee00, 0xc00121e240, 0xc001221c80)
	/usr/lib/golang/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc00030ee00, 0xc00121e240, {0xdbf7e8, 0xc0011ef000}, {0xdbf7e8, 0xc0011ef020}, 0x0)
	/usr/lib/golang/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc00030ee00, {0xdc85d8, 0xc00121e240}, 0x0)
	/usr/lib/golang/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc00030ee00)
	/usr/lib/golang/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc00030ee00, {0xc000d1df50, 0x5, 0x5})
	/usr/lib/golang/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/lib/golang/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002ad020, 0xc000868ca0)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000868ca0)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc0004d2f90, 0xc000868ca0)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x46?)
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 43
	/root/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:260 +0x1c5
make: *** [Makefile:91: manifests] Error 2

```

**Comment by sarroutbi** [comment]
My understanding is that it is something similar to [this issue](https://github.com/golang/go/issues/64812).

However, [fix](https://github.com/MadhavJivrajani/kubernetes/commit/2e34eb18d4e6b4b6e5d86eb6cdf382d162767085) is not working in this case, so I guess the best way to go is to wait for a more stable Go version and update the dependencies. This means changes in the code (some of the packages are not backwards compatible), so I prefer to have stable downstream version in OpenShift before.
